In [2]:
import torch
torch.__version__

'2.4.1+cu121'

In [3]:
### create a tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
## dimensions d'un tenseur
scalar.ndim

0

In [5]:
### recuperer le nombre du tenseur
scalar.item()

7

In [6]:
#### vector
## un vecteur est un tenseur unidimensionnel qui peut contenir des nombres
## examples: vecteur  = ([7, 7])
vector = torch.tensor([2, 2])
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
### matrice
matrix = torch.tensor([
    [7, 2],
    [5, 2]
])
matrix

tensor([[7, 2],
        [5, 2]])

In [9]:
matrix.shape, matrix.ndim

(torch.Size([2, 2]), 2)

In [10]:
### create tensor
tenseur = torch.tensor([[
    [1, 2],
    [3, 4],
    [5, 6]
]])
tenseur, tenseur.ndim, tenseur.shape

(tensor([[[1, 2],
          [3, 4],
          [5, 6]]]),
 3,
 torch.Size([1, 3, 2]))

In [11]:
### Tenseurs aléatoires

tensor_aleatoire = torch.rand(size = (2, 5))
tensor_aleatoire,


(tensor([[0.9702, 0.9418, 0.0110, 0.2005, 0.3743],
         [0.1366, 0.2806, 0.7040, 0.2281, 0.8299]]),)

In [12]:
tensor_aleatoire.dtype

torch.float32

In [13]:
tensor_images = torch.rand(size= (255, 255, 3))
tensor_images.shape, tensor_images.ndim, tensor_images.dtype, tensor_images

(torch.Size([255, 255, 3]),
 3,
 torch.float32,
 tensor([[[0.8587, 0.7694, 0.3979],
          [0.5123, 0.6140, 0.5510],
          [0.7998, 0.2324, 0.5298],
          ...,
          [0.9196, 0.6084, 0.4498],
          [0.5757, 0.8296, 0.6996],
          [0.6230, 0.1954, 0.9374]],
 
         [[0.6971, 0.0422, 0.3244],
          [0.3055, 0.0360, 0.8557],
          [0.6234, 0.9634, 0.9219],
          ...,
          [0.0752, 0.8539, 0.3026],
          [0.3993, 0.0288, 0.7396],
          [0.3203, 0.1455, 0.0755]],
 
         [[0.3559, 0.2902, 0.6145],
          [0.9447, 0.1853, 0.4154],
          [0.8131, 0.5577, 0.0709],
          ...,
          [0.8819, 0.1731, 0.8594],
          [0.7875, 0.5919, 0.7488],
          [0.7924, 0.7408, 0.8825]],
 
         ...,
 
         [[0.9641, 0.1044, 0.8590],
          [0.5295, 0.2967, 0.2198],
          [0.1126, 0.7620, 0.9519],
          ...,
          [0.4430, 0.2568, 0.1861],
          [0.8078, 0.4893, 0.2450],
          [0.4928, 0.7747, 0.1285]],
 


In [14]:
### create a tensor filling of zeros and ones
### zeros
tensor_zeros = torch.zeros(size = (2, 3))
tensor_zeros, tensor_zeros.dtype, tensor_zeros.shape, tensor_zeros.ndim

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32,
 torch.Size([2, 3]),
 2)

In [15]:
### ones
tensor_ones = torch.ones(size = (2, 3))
tensor_ones, tensor_ones.dtype, tensor_ones.shape, tensor_ones.ndim

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32,
 torch.Size([2, 3]),
 2)

In [16]:
### creer un plage et des tenseurs
plage_tenseurs = torch.range(0, 100) ## ceci peut renvoyer des messages d'attention
plage_tenseurs


<ipython-input-16-78649fa88ddb>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  plage_tenseurs = torch.range(0, 100) ## ceci peut renvoyer des messages d'attention


tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
         24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
         36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
         48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,
         60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
         72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
         84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
         96.,  97.,  98.,  99., 100.])

In [17]:
### ou ceci
plage_tensor = torch.arange(start = 0, end = 100, step = 10)
plage_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
plage_tensor.dtype

torch.int64

In [20]:
### types de données tensorielles
### Nous avons les données de type flottante( float(64, 32, 16, 8 et meme 7))
### par défaut pour les tenseurs nous utilisons float32
float_type = torch.tensor([2.0, 5.0, 8.0],
                          dtype = None,
                          device = None,
                          requires_grad=False)
float_type.dtype, float_type.shape, float_type.ndim


(torch.float32, torch.Size([3]), 1)

In [22]:
### create un tenseur de type float16, float8

float_16 = float_type.type(torch.float16)
float_16.dtype, float_16.shape, float_16.ndim

(torch.float16, torch.Size([3]), 1)

In [24]:
#loat_8 = float_type.type(torch.float8)
#float_8.dtype, float_8.shape, float_8.ndim

In [25]:
### les operations de mutliplication, d'addition, de soustraction et de division
tenseur = torch.tensor([1, 2, 3])
addition = tenseur + 10
soust = tenseur -10
multipkication = tenseur * 10
division = tenseur / 10
addition, soust, multipkication, division



(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [26]:
### ou en utilisant les fonctions add, mul(addition , multi et matmul pour les matrices)
addition = torch.add(tenseur, 10)
soust = torch.sub(tenseur, 10)
multipkication = torch.mul(tenseur, 10)
division = torch.div(tenseur, 10)
multi = torch.matmul(tenseur, tenseur)
addition, soust, multipkication, division, multi

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor(14))

In [27]:
tensor_1 = torch.tensor([1, 2, 5])
tensor_2 = torch.tensor([1, 2, 3])
torch.matmul(tensor_1, tensor_2)

tensor(20)

In [28]:
tensor_1 @ tensor_2

tensor(20)

In [29]:
(tensor_1, tensor_2)

(tensor([1, 2, 5]), tensor([1, 2, 3]))

In [32]:
### erreurs rencontrées en apprentissage profond(les erreurs de formes  des tensuers)
%time
tensor_a = torch.tensor([[0,5, 8],
                        [2, 8, 2.5],
                        [5, 7, 3]], dtype = torch.float32)
tensor_b = torch.tensor([[1,5, 3],
                        [3, 4, 7],
                        [5, 7, 2]], dtype = torch.float32)
torch.matmul(tensor_a, tensor_b)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs


tensor([[55.0000, 76.0000, 51.0000],
        [38.5000, 59.5000, 67.0000],
        [41.0000, 74.0000, 70.0000]])

In [33]:
### empiler une couche linéaire
torch.nn.Linear(in_features = 3, out_features = 3)

Linear(in_features=3, out_features=3, bias=True)

In [37]:

torch.manual_seed(42)
print(tensor_a.shape)
linear = torch.nn.Linear(in_features=3, out_features=3)
output = linear(tensor_a)
print(output.shape)

torch.Size([3, 3])
torch.Size([3, 3])


In [38]:
print(output)

tensor([[0.8904, 0.8014, 5.8751],
        [3.9548, 0.8418, 3.5308],
        [4.7321, 2.6176, 2.6030]], grad_fn=<AddmmBackward0>)


In [40]:
### Fonction d'agrégation (max, min sum, mean)

value = torch.arange(start = 1, end = 50, step = 15)
## maximum, minimum
maxi = value.max()
mini = value.min()
moy= value.type(torch.float32).mean()
maxi, mini, moy

(tensor(46), tensor(1), tensor(23.5000))

In [41]:
### ou plus simplement
maxi = torch.max(value)
mini = torch.min(value)
moy = torch.mean(value.type(torch.float32))
maxi, mini, moy

(tensor(46), tensor(1), tensor(23.5000))

In [42]:
### trouver la position d'une valeur
print(value)
position_max = torch.argmax(value)
position_min = torch.argmin(value)
position_max, position_min

tensor([ 1, 16, 31, 46])


(tensor(3), tensor(0))

In [43]:
print(tensor_b)
print(tensor_b.dtype)

tensor([[1., 5., 3.],
        [3., 4., 7.],
        [5., 7., 2.]])
torch.float32


In [45]:
## pour changer le type de données
tensor_b_8= tensor_b.type(torch.int8)
tensor_b_8.dtype

torch.int8

In [46]:
tensor_b_16= tensor_b.type(torch.float16)
tensor_b_64 = tensor_b.type(torch.float64)
tensor_b_64_int = tensor_b.type(torch.int64)
tensor_b_16.dtype, tensor_b_64.dtype, tensor_b_64_int.dtype

(torch.float16, torch.float64, torch.int64)

In [51]:
tensor_b

tensor([[1., 5., 3.],
        [3., 4., 7.],
        [5., 7., 2.]])

**Exercice sur les bases**

In [57]:
## Create a random tensor with shape (7, 7)
x = torch.rand(size = (7, 7), dtype =torch.float32)
x.shape, x.ndim, x.device, x.dtype

(torch.Size([7, 7]), 2, device(type='cpu'), torch.float32)

In [58]:
##Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
##(hint: you may have to transpose the second tensor).
y = torch.rand(size = (1, 7), dtype = torch.float32)
y.shape, y.ndim, y.device, y.dtype

mutil = torch.matmul(x, y.T)
mutil

tensor([[1.9515],
        [1.8143],
        [0.8592],
        [1.9192],
        [1.7141],
        [1.3533],
        [1.7107]])

In [60]:
mutil = torch.mm(x, y.T)
mutil

tensor([[1.9515],
        [1.8143],
        [0.8592],
        [1.9192],
        [1.7141],
        [1.3533],
        [1.7107]])

In [62]:
torch.manual_seed(0)
x = torch.rand(size = (7, 7), dtype =torch.float64)
y = torch.rand(size = (1, 7), dtype = torch.float64)
mutil = torch.mm(x, y.T)
mutil

tensor([[3.0041],
        [1.5887],
        [2.2483],
        [2.1121],
        [1.6430],
        [2.1082],
        [2.3913]], dtype=torch.float64)

In [63]:
torch.manual_seed(1234)
w = torch.rand(size = (2, 3), dtype =torch.float32)
z = torch.rand(size = (2, 3), dtype = torch.float32)
mutil = torch.mm(w, z.T)
mutil

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [64]:
torch.max(mutil), torch.min(mutil)

(tensor(0.5617), tensor(0.3647))

In [65]:
torch.argmax(mutil), torch.argmin(mutil)

(tensor(3), tensor(0))